---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/3/2021 10:29 PM
---

local HumanSound = {}

local base_sound = require('__base__/prototypes/entity/sounds')

function HumanSound.pistol()
    return base_sound.light_gunshot
end

function HumanSound.tank_gunshot()
    return base_sound.tank_gunshot
end

function HumanSound.machine_gun()
    return base_sound.submachine_gunshot
end

function HumanSound.heavy_machine_gun()
    return base_sound.gun_turret_gunshot
end

function HumanSound.sniper()
    return base_sound.heavy_gunshot
end

function HumanSound.generic_impact()
    return base_sound.generic_impact
end

function HumanSound.shotgun()
    return base_sound.shotgun
end

function HumanSound.pistol()
    return base_sound.light_gunshot
end

function HumanSound.death(volume)
    return {
        variations = {
            {
                filename = "__enemyracemanager_assets__/sound/human_die1.ogg",
                volume = volume
            },
            {
                filename = "__enemyracemanager_assets__/sound/human_die2.ogg",
                volume = volume
            },
            {
                filename = "__enemyracemanager_assets__/sound/human_die3.ogg",
                volume = volume
            },
        }
    }
end

function HumanSound.mining(volume)
    return {
        variations = {
            {
                filename = "__core__/sound/axe-mining-stone-1.ogg",
                volume = volume
            },
            {
                filename = "__core__/sound/axe-mining-stone-2.ogg",
                volume = volume
            },
            {
                filename = "__core__/sound/axe-mining-stone-3.ogg",
                volume = volume
            },
            {
                filename = "__core__/sound/axe-mining-stone-4.ogg",
                volume = volume
            },
            {
                filename = "__core__/sound/axe-mining-stone-5.ogg",
                volume = volume
            },
            {
                filename = "__core__/sound/axe-mining-stone-6.ogg",
                volume = volume
            },
            {
                filename = "__core__/sound/axe-mining-stone-7.ogg",
                volume = volume
            },
        }
    }
end

return HumanSound;