---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 10/23/2021 12:53 PM
---
require("global")

local sound_pack = {
    {
        filename = "__enemyracemanager_assets__/sound/base_under_attack.ogg",
        volume = 0.5
    }
}

local muted_sound = {
    filename = "__enemyracemanager_assets__/sound/empty-sound.ogg",
    volume = 0.0
}

for i = 1, settings.startup["erm-asset-base-destroyed-alert-chance"].value, 1 do
    table.insert(sound_pack, muted_sound)
end

if settings.startup["erm-asset-base-destroyed-alert-replace"].value then
    data.raw["utility-sounds"]["default"]["alert_destroyed"] =  {
        category = "alert",
        variations = sound_pack,
        aggregation = {
            max_count = 1,
            remove = true,
            count_already_playing = true
        },
    }
end