---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 10/23/2021 12:53 PM
---
require('global')
if DEBUG_MODE then

    --data.raw["projectile"]["wraith-rocket"]["action"]["action_delivery"]["target_effects"][1]['entity_name'] = 'erm-small-explosion-blood-0-5'
    --
    --data.raw["projectile"]["battlecruiser-yamato-projectile"]["action"]["action_delivery"]["target_effects"][1]['entity_name'] = 'erm-ball-explosion-blood-2'

end
