---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/16/2022 9:33 PM
---
data:extend {
    {
        type = "bool-setting",
        name = "erm-asset-projectile-enable-lighting",
        description = "erm-asset-projectile-enable-lighting",
        setting_type = "startup",
        default_value = true,
        order = "enemyracemanager-asset-001",
    },
    {
        type = "bool-setting",
        name = "erm-asset-base-destroyed-alert-replace",
        description = "erm-asset-base-destroyed-alert-replace",
        setting_type = "startup",
        default_value = true,
        order = "enemyracemanager-asset-002",
    },
    {
        type = "int-setting",
        name = "erm-asset-base-destroyed-alert-chance",
        description = "erm-asset-base-destroyed-alert-chance",
        setting_type = "startup",
        default_value = 3,
        allowed_values = {0,1,2,3,4,5,9},
        order = "enemyracemanager-asset-003",
    },
    {
        type = "int-setting",
        name = "erm-asset-army-destroyed-alert-chance",
        description = "erm-asset-army-destroyed-alert-chance",
        setting_type = "startup",
        default_value = 3,
        allowed_values = {0,1,2,3,4,5,9},
        order = "enemyracemanager-asset-004",
    },
}