---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/16/2022 9:33 PM
---
data:extend {
    {
        type = "bool-setting",
        name = "erm-asset-projectile-enable-lighting",
        description = "erm-asset-projectile-enable-lighting",
        setting_type = "startup",
        default_value = true,
        order = "enemyracemanager-asset-001",
    },
    {
        type = "int-setting",
        name = "erm-asset-destroyed-alert-chance",
        description = "erm-asset-destroyed-alert-chance",
        setting_type = "startup",
        default_value = 3,
        allowed_values = {0,1,2,3,4,9},
        order = "enemyracemanager-asset-002",
    },
}