---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/8/2022 11:12 PM
---

local force_sound_pack = {
    {
        filename = "__enemyracemanager_assets__/sound/force_under_attack.ogg",
        volume = 0.5
    }
}

local force_muted_sound = {
    filename = "__enemyracemanager_assets__/sound/empty-sound.ogg",
    volume = 0.0
}

for i = 1, settings.startup["erm-asset-army-destroyed-alert-chance"].value * 2, 1 do
    table.insert(force_sound_pack, force_muted_sound)
end

data:extend({
    {
        type = "sound",
        name = "erm-army-full-population",
        category = "gui-effect",
        filename = "__enemyracemanager_assets__/sound/full_population.ogg",
        aggregation = {
            max_count = 1,
            remove = true,
            count_already_playing = true
        },
        volume = 0.5
    },
    {
        type = "sound",
        name = "erm-army-base-under-attack",
        category = "alert",
        filename = "__enemyracemanager_assets__/sound/base_under_attack.ogg",
        aggregation = {
            max_count = 1,
            remove = true,
            count_already_playing = true
        },
        volume = 0.5
    },
    {
        type = "sound",
        name = "erm-army-force-under-attack",
        category = "alert",
        filename = "__enemyracemanager_assets__/sound/force_under_attack.ogg",
        aggregation = {
            max_count = 1,
            remove = true,
            count_already_playing = true
        },
        volume = 0.5
    },
    {
        type = "sound",
        name = "erm-army-force-under-attack-by-chance",
        category = "alert",
        variations = force_sound_pack,
        aggregation = {
            max_count = 1,
            remove = true,
            count_already_playing = true
        },
    }
})

local programmable_speaker = data.raw['programmable-speaker']['programmable-speaker']

for index, instrument in pairs(programmable_speaker.instruments) do
    if instrument.name == "alarms" then
        table.insert(programmable_speaker.instruments[index].notes, { 
            name="air-raid-siren",  
            sound = { filename = "__enemyracemanager_assets__/sound/air-raid-siren.ogg", preload = false }}
        )
        table.insert(programmable_speaker.instruments[index].notes, {
            name="air-raid-siren-2",
            sound = { filename = "__enemyracemanager_assets__/sound/siren-alarm.ogg", preload = false }}
        )
        table.insert(programmable_speaker.instruments[index].notes, {
            name="germany-eas",
            sound = { filename = "__enemyracemanager_assets__/sound/germany-eas-alarm.ogg", preload = false }}
        )
        table.insert(programmable_speaker.instruments[index].notes, {
            name="japan-eas",
            sound = { filename = "__enemyracemanager_assets__/sound/japan-eas-alarm.ogg", preload = false }}
        )
        table.insert(programmable_speaker.instruments[index].notes, {
            name="japan-j-alert",
            sound = { filename = "__enemyracemanager_assets__/sound/japan-eas-alarm-j-alert.ogg", preload = false }}
        )
        table.insert(programmable_speaker.instruments[index].notes, {
            name="finland-eas",
            sound = { filename = "__enemyracemanager_assets__/sound/finland-eas-alarm.ogg", preload = false }}
        )
        table.insert(programmable_speaker.instruments[index].notes, {
            name="denmark-eas",
            sound = { filename = "__enemyracemanager_assets__/sound/denmark-eas-alarm.ogg", preload = false }}
        )
    end
end
