---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 9/5/2022 9:20 PM
---

local SharedFunctions = require("prototypes/shared")

local fire_explosion = function(data)
    data["scale"] = data["scale"] or 1
    local explosion = {
        type = "explosion",
        name = "erm-fire-explosion-"..data["type"].."_"..data["subtype"].."-"..SharedFunctions.convert_scale(data["scale"]),
        flags = { "not-on-map" },
        subgroup = "explosions",
        order = "erm-fire-explosion"..data["type"].."_"..data["subtype"].."-"..SharedFunctions.convert_scale(data["scale"]),
        render_layer = "explosion",
        --rotate = true,
        --correct_rotation = true,
    }
    explosion["animations"] = {}
    for key, animation in pairs(data["animations"]) do
        explosion["animations"][key] = {
            filename = "__enemyracemanager_assets__/graphics/fire_explosions/"..data["type"].."_"..data["subtype"].."_v"..key..".png",
            width = animation["width"],
            height = animation["height"],
            line_length = animation["line_number"],
            frame_count = animation["frame_count"],
            animation_speed = animation["speed"],
            scale = animation["scale"]
        }
        explosion = SharedFunctions.process_glow(explosion, data, key)
        if animation["shift"] then
            explosion["animations"][key]["shift"] = animation["shift"]
        end
    end

    explosion = SharedFunctions.process_lighting(explosion, data)
    return explosion
end

data:extend({
    fire_explosion({
        type="air",
        subtype="normal",
        draw_as_glow = true,
        animations = {
            {
                width=320,
                height=317,
                line_number=9,
                frame_count=40,
                speed=0.5,
                scale=1
            },
            {
                width=320,
                height=322,
                line_number=9,
                frame_count=40,
                speed=0.5,
                scale=1
            },
            {
                width=320,
                height=351,
                line_number=9,
                frame_count=40,
                speed=0.5,
                scale=1
            }
        },
        scale=1
    }),

    fire_explosion({
        type="air",
        subtype="large",
        draw_as_glow = true,
        animations = {
            {
                width=320,
                height=267,
                line_number=9,
                frame_count=40,
                speed=0.5,
                scale=1,
                shift={0.5, 0.5}
            },
            {
                width=320,
                height=304,
                line_number=9,
                frame_count=40,
                speed=0.5,
                scale=1,
                shift={-1, 1}
            },
            {
                width=320,
                height=329,
                line_number=9,
                frame_count=40,
                speed=0.5,
                scale=1
            }
        },
        scale=1
    }),

    fire_explosion({
        type="ground",
        subtype="normal",
        draw_as_glow = true,
        animations = {
            {
                width=320,
                height=296,
                line_number=9,
                frame_count=35,
                speed=0.5,
                scale=1,
                shift={0,-2}
            },
            {
                width=320,
                height=354,
                line_number=8,
                frame_count=34,
                speed=0.5,
                scale=1,
                shift={0,-3}
            },
            {
                width=320,
                height=346,
                line_number=8,
                frame_count=34,
                speed=0.5,
                scale=1
            }
        },
        scale=1
    })
})