---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/6/2025 11:11 PM
---


data:extend(
    {
        {
            type = "sprite",
            name = "icon-erm_air_raid_radar",
            filename = "__enemyracemanager_assets__/graphics/air_raid_radar.png",
            priority = "extra-high-no-scale",
            width = 64,
            height = 64,
            flags = {"icon"}
        }

    }
)